const PDFDocument = require("pdfkit");

const generatePDF = (customer, entries, summary, res) => {
    const doc = new PDFDocument({ margin: 40 });

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader(
        "Content-Disposition",
        `attachment; filename=${customer.name}_ledger.pdf`
    );

    doc.pipe(res);

    // 📄 TITLE
    doc
        .fontSize(18)
        .text("Credza Ledger Statement", { align: "center" });

    doc.moveDown();

    // 👤 CUSTOMER INFO
    doc.fontSize(12).text(`Customer: ${customer.name}`);
    doc.text(`Phone: ${customer.phone}`);
    if (customer.location) doc.text(`Location: ${customer.location}`);

    doc.moveDown();

    // 📊 ENTRIES
    entries.forEach((entry, index) => {
        doc
            .fontSize(12)
            .text(`${index + 1}. ${entry.type.toUpperCase()}`, {
                underline: true,
            });

        if (entry.type === "credit") {
            entry.products.forEach((p) => {
                doc.text(`   ${p.name}  x${p.qty}  ₹${p.price}`);
            });
            doc.text(`   Total: ₹${entry.totalAmount}`);
        } else {
            doc.text(`   Paid: ₹${entry.totalAmount}`);
        }

        doc.text(`   Balance: ₹${entry.runningBalance}`);
        doc.text(
            `   Date: ${new Date(entry.createdAt).toLocaleString()}`
        );

        doc.moveDown();
    });

    // 📦 SUMMARY
    doc.moveDown();
    doc.fontSize(12).text("Summary", { underline: true });

    doc.text(`Total Credit: ₹${summary.totalCredit}`);
    doc.text(`Total Debit: ₹${summary.totalDebit}`);
    doc.text(`Final Balance: ₹${summary.balance}`);

    doc.moveDown();

    // Footer
    doc
        .fontSize(10)
        .text("Generated by Credza", { align: "center" });

    doc.end();
};

module.exports = generatePDF;