const PDFDocument = require("pdfkit");

// 💰 Format currency (Indian style)
const formatCurrency = (amount) => {
  return `₹${Number(amount || 0).toLocaleString("en-IN")}`;
};

const generatePDF = (customer, entries, summary, res, owner) => {
  const doc = new PDFDocument({ margin: 40 });

  // Headers
  res.setHeader("Content-Type", "application/pdf");
  res.setHeader(
    "Content-Disposition",
    `attachment; filename=${customer.name}_ledger.pdf`
  );

  doc.pipe(res);

  // ===== HEADER BACKGROUND =====
  doc.rect(0, 0, 612, 90).fill("#eef4ff");

  // ===== BRAND =====
  doc
    .fillColor("#2563eb")
    .fontSize(20)
    .text("Credza", 40, 35);

  // ===== SHOP DETAILS =====
  doc
    .fillColor("black")
    .fontSize(10)
    .text(owner?.shopName || "Credza User", 40, 55)
    .text(owner?.name || "")
    .text(owner?.phone || "");

  doc.moveDown(3);

  // ===== CUSTOMER BOX =====
  const customerTop = doc.y;

  doc
    .roundedRect(40, customerTop, 520, 70, 6)
    .stroke("#d1d5db");

  doc
    .fontSize(12)
    .text("Customer Details", 50, customerTop + 5, { underline: true });

  doc
    .fontSize(11)
    .text(`Name: ${customer.name}`, 50, customerTop + 25)
    .text(`Phone: ${customer.phone}`)
    .text(`Location: ${customer.location || "-"}`);

  doc.moveDown(4);

  // ===== TABLE HEADER =====
  const tableTop = doc.y;

  const col = {
    type: 50,
    details: 120,
    amount: 320,
    balance: 400,
    date: 480,
  };

  // Header background
  doc.rect(40, tableTop, 520, 20).fill("#f3f4f6");

  doc
    .fillColor("black")
    .fontSize(11)
    .text("Type", col.type, tableTop + 5)
    .text("Details", col.details, tableTop + 5)
    .text("Amount", col.amount, tableTop + 5, { align: "right", width: 60 })
    .text("Balance", col.balance, tableTop + 5, { align: "right", width: 60 })
    .text("Date", col.date, tableTop + 5);

  doc.moveDown();

  // ===== ENTRIES =====
  entries.forEach((entry) => {
    const y = doc.y;

    let details = "";
    if (entry.type === "credit") {
      details = entry.products
        .map((p) => `${p.name} x${p.qty}`)
        .join(", ");
    } else {
      details = "Payment";
    }

    doc
      .fontSize(10)
      .text(entry.type.toUpperCase(), col.type, y)
      .text(details, col.details, y, { width: 180 })
      .text(formatCurrency(entry.totalAmount), col.amount, y, {
        align: "right",
        width: 60,
      })
      .text(formatCurrency(entry.runningBalance), col.balance, y, {
        align: "right",
        width: 60,
      })
      .text(
        new Date(entry.createdAt).toLocaleDateString("en-IN"),
        col.date,
        y
      );

    doc.moveDown();
  });

  doc.moveDown(2);

  // ===== SUMMARY BOX =====
  const summaryY = doc.y;

  doc
    .roundedRect(350, summaryY, 210, 90, 6)
    .stroke("#d1d5db");

  doc
    .fontSize(12)
    .text("Summary", 360, summaryY + 10, { underline: true });

  doc
    .fontSize(11)
    .text(`Total Credit: ${formatCurrency(summary.totalCredit)}`, 360)
    .text(`Total Debit: ${formatCurrency(summary.totalDebit)}`)
    .text(`Final Balance: ${formatCurrency(summary.balance)}`);

  doc.moveDown(5);

  // ===== FOOTER =====
  doc
    .fontSize(10)
    .fillColor("gray")
    .text("Generated by Credza", { align: "center" });

  doc.end();
};

module.exports = generatePDF;